### ISSUE TITLE
Pointer access violation in remove_tree(Node *node)

### ISSUE THREAD

**Issue by fteicht** [bonetblai/rollout-iw#1]
Hi Blai,

When you call remove_tree(child) while iterating over a node's children, you (recursively) delete the child (line 371 in node.h) before accessing its sibling (end of for loop in line 369), implying a segfault.

You need to make two (obvious) small modifications to correct the bug. Basically, it consists in saving a child's sibling before deleting the child and actually moving to the sibling.

Since I have forked your project and substantially changed it, I prefer copying/pasting the correction here rather than doing a pull request with my fork (too far from your project now).

The first modification is in the function remove_tree which becomes:

```
inline void remove_tree(Node *node) {
    Node *sibling = nullptr;
    for( Node *child = node->first_child_; child != nullptr; child = sibling ) {
        sibling = child->sibling_;
        remove_tree(child);
    }
    delete node;
}
```

The second modification is in the advance(Action action) function where you need to replace lines 103-110 with the following lines:

```
        Node *selected = nullptr;
        Node *sibling = nullptr;
        for( Node *child = first_child_; child != nullptr; child = sibling ) {
            sibling = child->sibling_;
            if( child->action_ == action )
                selected = child;
            else
                remove_tree(child);
        }
        assert(selected != nullptr);
```

Hope it helps.

Cheers,
Florent

**Comment by bonetblai** [comment]
Hi Florent. Thanks for the update on this. Bug fixed following your advice!
