### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by ggdupont** [bonetblai/rollout-iw#2]
Hi,
I might use your implementation of IW but the fact that your code doesn't declare any license could be a show-stopper. Would it be possible for you to add an open license?

thx

**Comment by bonetblai** [comment]
Hi, What kind of license do you need? There are many options and not sure what are your needs. In principle, I won't have a problem to add a license. What kind of use do you have in mind?

**Comment by ggdupont** [comment]
Well it really depends on your targets for the project. 
In our case (usage in corporate environment), I would suggest one that does not enforce copyleft.

Among of the simplest ones and largely used in research is the [MIT license](https://opensource.org/licenses/MIT) or the [BSD license](https://opensource.org/licenses/BSD-3-Clause) which are basically just here to protect your copyright and avoid any responsibilities in the use of your code.

**Comment by bonetblai** [comment]
Done! BSD-3 license. If you find the software useful, let me know. I'll be happy to know that someone has found a practical use of the software. Enjoy!

**Comment by ggdupont** [comment]
Thx a lot!
I'll make sure your work is credited on our usage/communication.
